# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    permissions: write-all
    runs-on: ubuntu-latest

    env:
      BASE_URL: "https://www.saucedemo.com"
      USER_STANDARD: "standard_user"
      USER_LOCKED_OUT: "locked_out_user"
      USER_PROBLEM: "problem_user"
      USER_PERFORMANCE: "performance_glitch_user"
      USER_ERROR: "error_user"
      USER_VISUAL: "visual_user"
      PASSWORD: "secret_sauce"

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --logger "trx"

    - name: Test Reporter
      # You may pin to the exact commit or the version.
      # uses: dorny/test-reporter@31a54ee7ebcacc03a09ea97a7e5465a47b84aea5
      uses: dorny/test-reporter@v1.9.1
      with:
        name: Name of the report
        # Comma-separated list of paths to test results
        # Supports wildcards via [fast-glob](https://github.com/mrmlnc/fast-glob)
        # All matched result files must be of same format    
        path: "**/TestResults/*.trx"
        reporter: dotnet-trx
