# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    permissions: write-all
    runs-on: ubuntu-latest

    strategy:
      matrix:
        category: [Login, Checkout, ErrorUser, VisualUser, Cart]

    env:
      USER_STANDARD: "standard_user"
      USER_LOCKED_OUT: "locked_out_user"
      USER_PROBLEM: "problem_user"
      USER_PERFORMANCE: "performance_glitch_user"
      USER_ERROR: "error_user"
      USER_VISUAL: "visual_user"
      PASSWORD: "secret_sauce"

    steps:
    - uses: actions/checkout@v4
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test ${{ matrix.category }}
      run: dotnet test --no-build --verbosity normal --logger "trx" --filter TestCategory=${{ matrix.category }}

    - name: Test Reporter
      uses: dorny/test-reporter@v1.9.1
      with:
        name: Report for ${{ matrix.category }} tests   
        path: "**/TestResults/*.trx"
        reporter: dotnet-trx
